"""add_brand_kit_and_rendered_video_tables

Revision ID: 865c863df6b0
Revises: 5edf2d4fad3d
Create Date: 2026-10-06 04:49:52.343844+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '865c863df6b0'
down_revision: Union[str, None] = '5edf2d4fad3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_brand_kit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('voice_engine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('voice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar_engine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar_model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_hex', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accent_hex', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtitle_highlight_hex', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('background_hex', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('watermark_logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intro_bumper_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('outro_bumper_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('font_family', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_brand_kit_client_id'), 'client_brand_kit', ['client_id'], unique=True)
    op.create_table('rendered_video',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('script_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('video_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('social_caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_profile.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['script.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rendered_video_client_id'), 'rendered_video', ['client_id'], unique=False)
    op.create_index(op.f('ix_rendered_video_created_at'), 'rendered_video', ['created_at'], unique=False)
    op.create_index(op.f('ix_rendered_video_script_id'), 'rendered_video', ['script_id'], unique=False)
    op.create_index(op.f('ix_rendered_video_status'), 'rendered_video', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rendered_video_status'), table_name='rendered_video')
    op.drop_index(op.f('ix_rendered_video_script_id'), table_name='rendered_video')
    op.drop_index(op.f('ix_rendered_video_created_at'), table_name='rendered_video')
    op.drop_index(op.f('ix_rendered_video_client_id'), table_name='rendered_video')
    op.drop_table('rendered_video')
    op.drop_index(op.f('ix_client_brand_kit_client_id'), table_name='client_brand_kit')
    op.drop_table('client_brand_kit')
    # ### end Alembic commands ###
