"""add_client_and_script_tables

Revision ID: 5edf2d4fad3d
Revises: 56eb2315edb3
Create Date: 2026-10-06 04:11:32.571949+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5edf2d4fad3d'
down_revision: Union[str, None] = '56eb2315edb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_profile_is_active'), 'client_profile', ['is_active'], unique=False)
    op.create_index(op.f('ix_client_profile_name'), 'client_profile', ['name'], unique=False)
    op.create_index(op.f('ix_client_profile_slug'), 'client_profile', ['slug'], unique=True)
    op.create_table('client_persona',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('persona_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tone_of_voice', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_audience', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_cta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_persona_client_id'), 'client_persona', ['client_id'], unique=True)
    op.create_table('client_topic_filter',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('industries', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('focus_keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('excluded_keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weight_actionability', sa.Float(), nullable=False),
    sa.Column('weight_economic', sa.Float(), nullable=False),
    sa.Column('weight_regulatory', sa.Float(), nullable=False),
    sa.Column('weight_novelty', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_topic_filter_client_id'), 'client_topic_filter', ['client_id'], unique=True)
    op.create_table('script',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('persona_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_estimated_duration_sec', sa.Integer(), nullable=False),
    sa.Column('call_to_action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_article_id'), 'script', ['article_id'], unique=False)
    op.create_index(op.f('ix_script_client_id'), 'script', ['client_id'], unique=False)
    op.create_index(op.f('ix_script_created_at'), 'script', ['created_at'], unique=False)
    op.create_index(op.f('ix_script_status'), 'script', ['status'], unique=False)
    op.create_table('script_beat',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('script_id', sa.Uuid(), nullable=False),
    sa.Column('beat_index', sa.Integer(), nullable=False),
    sa.Column('beat_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spoken_script', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visual_directive', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('whiteboard_directive', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['script.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_beat_beat_index'), 'script_beat', ['beat_index'], unique=False)
    op.create_index(op.f('ix_script_beat_beat_type'), 'script_beat', ['beat_type'], unique=False)
    op.create_index(op.f('ix_script_beat_script_id'), 'script_beat', ['script_id'], unique=False)
    op.create_table('script_claim_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('script_id', sa.Uuid(), nullable=False),
    sa.Column('beat_index', sa.Integer(), nullable=False),
    sa.Column('claim_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verified_citation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_verbatim_quote', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_grounded', sa.Boolean(), nullable=False),
    sa.Column('audit_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['script.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_claim_audit_beat_index'), 'script_claim_audit', ['beat_index'], unique=False)
    op.create_index(op.f('ix_script_claim_audit_is_grounded'), 'script_claim_audit', ['is_grounded'], unique=False)
    op.create_index(op.f('ix_script_claim_audit_script_id'), 'script_claim_audit', ['script_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_script_claim_audit_script_id'), table_name='script_claim_audit')
    op.drop_index(op.f('ix_script_claim_audit_is_grounded'), table_name='script_claim_audit')
    op.drop_index(op.f('ix_script_claim_audit_beat_index'), table_name='script_claim_audit')
    op.drop_table('script_claim_audit')
    op.drop_index(op.f('ix_script_beat_script_id'), table_name='script_beat')
    op.drop_index(op.f('ix_script_beat_beat_type'), table_name='script_beat')
    op.drop_index(op.f('ix_script_beat_beat_index'), table_name='script_beat')
    op.drop_table('script_beat')
    op.drop_index(op.f('ix_script_status'), table_name='script')
    op.drop_index(op.f('ix_script_created_at'), table_name='script')
    op.drop_index(op.f('ix_script_client_id'), table_name='script')
    op.drop_index(op.f('ix_script_article_id'), table_name='script')
    op.drop_table('script')
    op.drop_index(op.f('ix_client_topic_filter_client_id'), table_name='client_topic_filter')
    op.drop_table('client_topic_filter')
    op.drop_index(op.f('ix_client_persona_client_id'), table_name='client_persona')
    op.drop_table('client_persona')
    op.drop_index(op.f('ix_client_profile_slug'), table_name='client_profile')
    op.drop_index(op.f('ix_client_profile_name'), table_name='client_profile')
    op.drop_index(op.f('ix_client_profile_is_active'), table_name='client_profile')
    op.drop_table('client_profile')
    # ### end Alembic commands ###
