"""create_news_tables

Revision ID: 56eb2315edb3
Revises: 
Create Date: 2026-10-05 06:24:55.531535+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '56eb2315edb3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newssource',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feed_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feed_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trust_tier', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newssource_feed_url'), 'newssource', ['feed_url'], unique=True)
    op.create_index(op.f('ix_newssource_is_active'), 'newssource', ['is_active'], unique=False)
    op.create_index(op.f('ix_newssource_name'), 'newssource', ['name'], unique=False)
    op.create_table('article',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['newssource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_content_hash'), 'article', ['content_hash'], unique=False)
    op.create_index(op.f('ix_article_created_at'), 'article', ['created_at'], unique=False)
    op.create_index(op.f('ix_article_published_at'), 'article', ['published_at'], unique=False)
    op.create_index(op.f('ix_article_source_id'), 'article', ['source_id'], unique=False)
    op.create_index(op.f('ix_article_status'), 'article', ['status'], unique=False)
    op.create_index(op.f('ix_article_title'), 'article', ['title'], unique=False)
    op.create_index(op.f('ix_article_url'), 'article', ['url'], unique=True)
    op.create_table('articlescore',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('actionability', sa.Float(), nullable=False),
    sa.Column('economic_impact', sa.Float(), nullable=False),
    sa.Column('regulatory_impact', sa.Float(), nullable=False),
    sa.Column('novelty', sa.Float(), nullable=False),
    sa.Column('reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('scored_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articlescore_article_id'), 'articlescore', ['article_id'], unique=False)
    op.create_index(op.f('ix_articlescore_client_id'), 'articlescore', ['client_id'], unique=False)
    op.create_index(op.f('ix_articlescore_composite_score'), 'articlescore', ['composite_score'], unique=False)
    op.create_index(op.f('ix_articlescore_is_selected'), 'articlescore', ['is_selected'], unique=False)
    op.create_table('articleverification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('secondary_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secondary_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agreement_score', sa.Float(), nullable=False),
    sa.Column('corroboration_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articleverification_article_id'), 'articleverification', ['article_id'], unique=True)
    op.create_index(op.f('ix_articleverification_is_verified'), 'articleverification', ['is_verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articleverification_is_verified'), table_name='articleverification')
    op.drop_index(op.f('ix_articleverification_article_id'), table_name='articleverification')
    op.drop_table('articleverification')
    op.drop_index(op.f('ix_articlescore_is_selected'), table_name='articlescore')
    op.drop_index(op.f('ix_articlescore_composite_score'), table_name='articlescore')
    op.drop_index(op.f('ix_articlescore_client_id'), table_name='articlescore')
    op.drop_index(op.f('ix_articlescore_article_id'), table_name='articlescore')
    op.drop_table('articlescore')
    op.drop_index(op.f('ix_article_url'), table_name='article')
    op.drop_index(op.f('ix_article_title'), table_name='article')
    op.drop_index(op.f('ix_article_status'), table_name='article')
    op.drop_index(op.f('ix_article_source_id'), table_name='article')
    op.drop_index(op.f('ix_article_published_at'), table_name='article')
    op.drop_index(op.f('ix_article_created_at'), table_name='article')
    op.drop_index(op.f('ix_article_content_hash'), table_name='article')
    op.drop_table('article')
    op.drop_index(op.f('ix_newssource_name'), table_name='newssource')
    op.drop_index(op.f('ix_newssource_is_active'), table_name='newssource')
    op.drop_index(op.f('ix_newssource_feed_url'), table_name='newssource')
    op.drop_table('newssource')
    # ### end Alembic commands ###
