"""Pydantic request and response schemas (DTOs)."""
from app.schemas.auth import AccountProfile, LoginRequest, TokenResponse
from app.schemas.client import (
    ClientBrandKitCreate,
    ClientBrandKitRead,
    ClientBrandKitUpdate,
    ClientDetailRead,
    ClientPersonaCreate,
    ClientPersonaRead,
    ClientPersonaUpdate,
    ClientProfileCreate,
    ClientProfileRead,
    ClientProfileUpdate,
    ClientTopicFilterCreate,
    ClientTopicFilterRead,
    ClientTopicFilterUpdate,
)
from app.schemas.media import (
    RenderedVideoCreate,
    RenderedVideoRead,
    VideoRenderRequest,
    VideoRenderResultDTO,
)
from app.schemas.news import (
    ArticleCreate,
    ArticleDetailRead,
    ArticleRead,
    ArticleScoreRead,
    ArticleVerificationRead,
    IngestionSummaryDTO,
    NewsSourceCreate,
    NewsSourceRead,
    ScreenedCandidateDTO,
)
from app.schemas.script import (
    ScriptBeatCreate,
    ScriptBeatRead,
    ScriptClaimAuditCreate,
    ScriptClaimAuditRead,
    ScriptCreate,
    ScriptDetailRead,
    ScriptGenerationRequest,
    ScriptGenerationResultDTO,
    ScriptGroundingSummary,
    ScriptRead,
)

__all__: list[str] = [
    "LoginRequest",
    "TokenResponse",
    "AccountProfile",
    "NewsSourceCreate",
    "NewsSourceRead",
    "ArticleCreate",
    "ArticleRead",
    "ArticleDetailRead",
    "ArticleVerificationRead",
    "ArticleScoreRead",
    "ScreenedCandidateDTO",
    "IngestionSummaryDTO",
    "ClientProfileCreate",
    "ClientProfileRead",
    "ClientProfileUpdate",
    "ClientDetailRead",
    "ClientPersonaCreate",
    "ClientPersonaRead",
    "ClientPersonaUpdate",
    "ClientTopicFilterCreate",
    "ClientTopicFilterRead",
    "ClientTopicFilterUpdate",
    "ClientBrandKitCreate",
    "ClientBrandKitRead",
    "ClientBrandKitUpdate",
    "ScriptCreate",
    "ScriptRead",
    "ScriptDetailRead",
    "ScriptBeatCreate",
    "ScriptBeatRead",
    "ScriptClaimAuditCreate",
    "ScriptClaimAuditRead",
    "ScriptGroundingSummary",
    "ScriptGenerationRequest",
    "ScriptGenerationResultDTO",
    "RenderedVideoCreate",
    "RenderedVideoRead",
    "VideoRenderRequest",
    "VideoRenderResultDTO",
]
